### ISSUE TITLE
ImportError: cannot import name 'cli'

### ISSUE THREAD

**Issue by jbclaramonte** [ottogroup/clash#2]
Hello

I'm giving clash a try but I have an error when using it.
I have installed it in cloud shell using a virtual env
but when I run it I have the following error:

`$ clash init`
`Traceback (most recent call last):`
`  File "/home/jbclaramonte_ext/clash/bin/clash", line 6, in <module>`
`    from pyclash.clash import cli`
`ImportError: cannot import name 'cli'`

What am I doing wrong ?

**Comment by mrahbar** [comment]
@jbclaramonte nice that you given clash a try. The reason for the error is that the PyPi version need to be updated to the new code base @mikeczech . You are currently probably better off installing the package locally yourself via:
```
git clone git@github.com:ottogroup/clash.git
cd clash\python
pip install .
clash init
```
Clash is still a young project and we hope this kind of early issues are gone soon.
